# Generated by Django 5.1.3 on 2025-03-26 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(blank=True, null=True, upload_to="")),
                ("anoDeCriacao", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=100)),
                ("informacoes", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("capa", models.ImageField(blank=True, null=True, upload_to="")),
                ("nome", models.CharField(max_length=100)),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Albuns",
                        to="bandas.banda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Musica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("link", models.CharField(max_length=100)),
                ("letra", models.TextField(blank=True, default=1, null=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Musicas",
                        to="bandas.album",
                    ),
                ),
                (
                    "banda",
                    models.ManyToManyField(related_name="musicas", to="bandas.banda"),
                ),
            ],
        ),
    ]
