# Generated by Django 5.1.3 on 2025-04-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musica",
            name="banda",
        ),
    ]
