# Generated by Django 5.1.3 on 2025-03-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artigos", "0002_comentario_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="conteudo",
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
